version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers

jobs:
  bobby:
    executor: my-executor
    steps:
      - run: echo "outside the executor"

  sally:
    executor: my-executor
    steps:
      - run: echo "outside the executor"

workflows:
  version: 2.1
  bobby&sally:
    jobs:
      -bobby
      -sally
